title: "Third workshop on advanced methods in theoretical neuroscience"
theme: jekyll-theme-slate
description: "June 27-29, 2018 • Göttingen, Germany"
github:
  is_project_page: true
  repository_url: "http://www.wamtn.info/"
